# Generated by Django 5.0.3 on 2024-04-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_category_recipe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
